sudo: required
services:
  - docker 

before_install:
  - docker build -t vaipra1305/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaipra1305/docker-react npm run test -- --coverage